<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\CleanArchWorkerService.Application\CleanArchWorkerService.Application.csproj" />
    <ProjectReference Include="..\CleanArchWorkerService.Domain\CleanArchWorkerService.Domain.csproj" />
    <ProjectReference Include="..\CleanArchWorkerService.Infrastructure\CleanArchWorkerService.Infrastructure.csproj" />
    <ProjectReference Include="..\CleanArchWorkerService.ServiceDefaults\CleanArchWorkerService.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dorn.Messaging" />
    <PackageReference Include="Dorn.Messaging.Contracts" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
