<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <Protobuf Include="Protos\todo.proto" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanArchGrpcService.Application\CleanArchGrpcService.Application.csproj" />
    <ProjectReference Include="..\CleanArchGrpcService.Infrastructure\CleanArchGrpcService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dorn.Messaging" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
