<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CleanArchWorkerService.Domain\CleanArchWorkerService.Domain.csproj" />
    <ProjectReference Include="..\..\src\CleanArchWorkerService.Application\CleanArchWorkerService.Application.csproj" />
    <ProjectReference Include="..\..\src\CleanArchWorkerService.Infrastructure\CleanArchWorkerService.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\CleanArchWorkerService.Worker\CleanArchWorkerService.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dorn.Messaging.Contracts" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
