<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\CleanArchGrpcService.Domain\CleanArchGrpcService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dorn.Messaging.Contracts" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
